<center><h2> Channel Spyder Summary Comparison

#### Import Required Python Pakcages

In [1]:
import numpy as np
from faulthandler import is_enabled
from webbrowser import get
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.action_chains import ActionChains
import time
from bs4 import BeautifulSoup
import datetime as dt
from functools import reduce


options = webdriver.ChromeOptions()
options.add_argument(r"--user-data-dir=C:\Users\Fahad Razzaq\AppData\Local\Google\Chrome\User Data\CS_comparison1")


driver = webdriver.Chrome(options=options)  #Opening selenium
driver.get('https://www.channelspyder.com/inventory/inventory_list?file_type=1&upload_type=0&limit=200')    #Opening Amazon Inventory Page

### Get current date

In [2]:
from datetime import timedelta
from datetime import date

current_date = date.today()

### Inventory Files:

In [3]:
def parse_page(driver):
    """
    This function parses the webpage data using BeautifulSoup and stores it in a Pandas dataframe.
    
    Parameters:
    driver (WebDriver): A Selenium WebDriver object representing the current webpage.
    
    Returns:
    df (DataFrame): A Pandas DataFrame object containing the data from the webpage.
    """
    
    # Wait for the page to fully load before trying to parse the data
    WebDriverWait(driver, 300).until( lambda driver: driver.execute_script('return document.readyState') == 'complete')
    
    # Get the HTML source code of the page
    scr = driver.page_source
    
    # Use BeautifulSoup to parse the HTML source code
    soup = BeautifulSoup(scr, 'lxml')
    
    # Find the div element with the class "main-container container-fluid"
    table =soup.find("div", attrs ={"class":"main-container container-fluid"})
    
    # Find all th (table header) elements within the div element
    headers = table.findAll('th')
    
    # Create a list of the header text, stripped of leading/trailing white space
    headerlist =[h.text.strip() for h in headers]
    
    # Find all tr (table row) elements within the div element
    rows = table.findAll('tr')[0:]
    
    # Create a list of lists, where each inner list represents a row of data
    records = [[td.getText().strip() for td in rows[i].findAll('td')[0:]] for i in range(len(rows))]
    
    # Create a Pandas DataFrame from the records list, using the headerlist as the column names
    df = pd.DataFrame(records, columns=headerlist)
    
    return df


#### Call function to parse Inventory table

In [77]:
df = parse_page(driver).loc[1:]
df['Total in Main'] = df['Total in Main'].astype(int)

df = df.loc[df['Total in Main'] >= 50000]

df.head(20)

# File Name Channel/Warehouse               Type Method  Total in Main  \
1    1  Download        Parts Auth          Inventory  Timer         533767   
2    2  Download          Keystone          Inventory  Timer         146720   
3    3  Download               PFG          Inventory  Timer          88515   
5    5  Download     Dorman Direct  Inventory - Stock  Timer          81759   
9    9  Download               LKQ          Inventory  Timer          76668   
10  10  Download       Motor State          Inventory  Timer         104950   
14  14  Download        Wheel Pros          Inventory  Timer          64315   
15  15  Download               NPW          Inventory  Timer         293573   
16  16  Download        Parts Auth          Inventory  Timer         533984   
17  17  Download          Keystone          Inventory  Timer         146518   
18  18  Download               PFG          Inventory  Timer          88522   
20  20  Download            Turn14          Inventory  Timer         594586   
21  21  Download     Dorman Direct  Inventory - Stock  Timer          81753   
24  24  Download               LKQ          Inventory  Timer          76640   
26  26  Download       Motor State          Inventory  Timer         104929   
29  29  Download        Wheel Pros          Inventory  Timer          64315   
31  31  Download               NPW          Inventory  Timer         293653   
32  32  Download        Parts Auth          Inventory  Timer         533398   
33  33  Download          Keystone          Inventory  Timer         146518   
34  34  Download               PFG          Inventory  Timer          88526   

   Not Added Final Total In Stock                   Status  \
1      38256      495511   450279  Success - Saved Locally   
2      62178       84542    66192  Success - Saved Locally   
3          0       88515    64478  Success - Saved Locally   
5      18830       62929    52630  Success - Saved Locally   
9          0       76668    68296  Success - Saved Locally   
10     51927       53023    43688  Success - Saved Locally   
14     39327       24988    14171  Success - Saved Locally   
15    105274      188299    97035  Success - Saved Locally   
16     38183      495801   450705  Success - Saved Locally   
17     61911       84607    66315  Success - Saved Locally   
18         0       88522    64477  Success - Saved Locally   
20    250761      343825    70285  Success - Saved Locally   
21     18824       62929    52751  Success - Saved Locally   
24         0       76640    68145  Success - Saved Locally   
26     51924       53005    43453  Success - Saved Locally   
29     39327       24988    14171  Success - Saved Locally   
31    105301      188352    97114  Success - Saved Locally   
32     37993      495405   450690  Success - Saved Locally   
33     61911       84607    66315  Success - Saved Locally   
34         0       88526    64467  Success - Saved Locally   

               Uploaded  
1   2023-01-06 05:31:37  
2   2023-01-06 04:32:13  
3   2023-01-06 03:01:43  
5   2023-01-05 17:34:05  
9   2023-01-05 17:01:38  
10  2023-01-05 17:01:35  
14  2023-01-05 16:01:39  
15  2023-01-05 15:31:40  
16  2023-01-05 05:31:33  
17  2023-01-05 04:32:09  
18  2023-01-05 03:01:38  
20  2023-01-05 01:40:30  
21  2023-01-04 17:33:57  
24  2023-01-04 17:01:34  
26  2023-01-04 17:01:31  
29  2023-01-04 16:01:34  
31  2023-01-04 15:31:35  
32  2023-01-04 05:31:29  
33  2023-01-04 04:32:12  
34  2023-01-04 03:01:34

### Convert features into Numeric

In [78]:
df["Total in Main"] = df["Total in Main"].astype(int)
df["Final Total"] = df["Final Total"].astype(int)
df["Not Added"] = df["Not Added"].replace("N/A", 0)

df["Not Added"] = df["Not Added"].astype(int)
df["In Stock"] = df["In Stock"].astype(int)


df['Date'] = df['Uploaded'].apply(lambda x : pd.to_datetime(str(x)))
df['Date'] = df['Date'].dt.date

In [95]:
df = df.groupby(["Channel/Warehouse", "Date"]).head(1).sort_values(by = ["Channel/Warehouse", "Date"], ascending = False)
df

# File Name Channel/Warehouse               Type Method  Total in Main  \
14    14  Download        Wheel Pros          Inventory  Timer          64315   
29    29  Download        Wheel Pros          Inventory  Timer          64315   
45    45  Download        Wheel Pros          Inventory  Timer          64315   
62    62  Download        Wheel Pros          Inventory  Timer          64315   
162  162  Download        Wheel Pros          Inventory  Timer          64315   
20    20  Download            Turn14          Inventory  Timer         594586   
36    36  Download            Turn14          Inventory  Timer         594480   
52    52  Download            Turn14          Inventory  Timer         594476   
68    68  Download            Turn14          Inventory  Timer         594476   
160  160  Download            Turn14          Inventory  Timer         594462   
1      1  Download        Parts Auth          Inventory  Timer         533767   
16    16  Download        Parts Auth          Inventory  Timer         533984   
32    32  Download        Parts Auth          Inventory  Timer         533398   
48    48  Download        Parts Auth          Inventory  Timer         533325   
64    64  Download        Parts Auth          Inventory  Timer         532925   
3      3  Download               PFG          Inventory  Timer          88515   
18    18  Download               PFG          Inventory  Timer          88522   
34    34  Download               PFG          Inventory  Timer          88526   
66    66  Download               PFG          Inventory  Timer          88527   
15    15  Download               NPW          Inventory  Timer         293573   
31    31  Download               NPW          Inventory  Timer         293653   
47    47  Download               NPW          Inventory  Timer         293771   
63    63  Download               NPW          Inventory  Timer         293818   
168  168  Download               NPW          Inventory  Timer         293935   
10    10  Download       Motor State          Inventory  Timer         104950   
26    26  Download       Motor State          Inventory  Timer         104929   
42    42  Download       Motor State          Inventory  Timer         104986   
58    58  Download       Motor State          Inventory  Timer         104989   
149  149  Download       Motor State          Inventory  Timer         103518   
9      9  Download               LKQ          Inventory  Timer          76668   
24    24  Download               LKQ          Inventory  Timer          76640   
40    40  Download               LKQ          Inventory  Timer          76012   
57    57  Download               LKQ          Inventory  Timer          76027   
148  148  Download               LKQ          Inventory  Timer          76053   
2      2  Download          Keystone          Inventory  Timer         146720   
17    17  Download          Keystone          Inventory  Timer         146518   
33    33  Download          Keystone          Inventory  Timer         146518   
49    49  Download          Keystone          Inventory  Timer         146550   
65    65  Download          Keystone          Inventory  Timer         146657   
5      5  Download     Dorman Direct  Inventory - Stock  Timer          81759   
21    21  Download     Dorman Direct  Inventory - Stock  Timer          81753   
37    37  Download     Dorman Direct  Inventory - Stock  Timer          81746   
53    53  Download     Dorman Direct  Inventory - Stock  Timer          81798   
140  140  Download     Dorman Direct  Inventory - Stock  Timer          81758   

     Not Added  Final Total  In Stock                   Status  \
14       39327        24988     14171  Success - Saved Locally   
29       39327        24988     14171  Success - Saved Locally   
45       39327        24988     14171  Success - Saved Locally   
62       39327        24988     14171  Success - Saved Locally   
162      39327        24988    

#### Make Comparison Table

In [69]:
dff_comparison = pd.DataFrame()
dff_diff = pd.DataFrame()

In [96]:
### Create list for storing results
warehouse_list = []
Comparison_list = []
difference = []


### Iterate over each warehouse name for its comparison
for label in df["Channel/Warehouse"].unique():
#     print(label)

    ### get the latest and 2nd last available inventory
    stock_latest = df.loc[df["Channel/Warehouse"] == label, ['Total in Main', 'Not Added', 'Final Total', 'In Stock']].values[0]
    stock_previous = df.loc[df["Channel/Warehouse"] == label, ['Total in Main', 'Not Added', 'Final Total', 'In Stock']].values[1]
    display(stock_latest)
    
    ### Calcu;ate actual difference of latest and previous results
    diff_actual = stock_latest - stock_previous
    
    ## Append difference results for each warehouse in differnece list
    difference.append(diff_actual)
    
    #### Calculate average comparison
    comparison = (abs(stock_latest - stock_previous)/stock_previous) * 100

    ## Append comparison results for each warehouse in comparison list
    Comparison_list.append(comparison)

    
    ### Append column_label in warehouse list
    warehouse_list.append(label)

    
### Create dataframe of comparison list and add warehouse column
dff_comparison = pd.DataFrame(Comparison_list)
dff_comparison['Warehouse'] = warehouse_list
display(dff_comparison)

### Create dataframe of difference list and add warehouse column
dff_diff  = pd.DataFrame(difference)
dff_diff['Warehouse'] = warehouse_list
display(dff_diff)

### Merge both dataframe and use warehouse as key
df_Inv_comparison = pd.merge(dff_diff, dff_comparison, on = "Warehouse")
display(df_Inv_comparison)    
### Rename all columns
df_Inv_comparison.columns = ['Total in Main Difference', 'Not Added Difference', 'Final Total Difference', 'In Stock Difference', 'Warehouse',
                                 'Total in Main Difference %', 'Not Added Difference %', 'Final Total Difference %', 'In Stock Difference %']
### Put warehouse feature in start
warehouse = df_Inv_comparison.pop("Warehouse")
df_Inv_comparison.insert(0, 'Warehouse', warehouse)
### Replace N/As
df_Inv_comparison.fillna(0, inplace = True)
display(df_Inv_comparison)


array([64315, 39327, 24988, 14171])

array([594586, 250761, 343825,  70285])

array([533767,  38256, 495511, 450279])

array([88515,     0, 88515, 64478])

C:\Users\Fahad Razzaq\AppData\Local\Temp\ipykernel_5060\2031040558.py:23: RuntimeWarning: invalid value encountered in true_divide
  comparison = (abs(stock_latest - stock_previous)/stock_previous) * 100


array([293573, 105274, 188299,  97035])

array([104950,  51927,  53023,  43688])

array([76668,     0, 76668, 68296])

C:\Users\Fahad Razzaq\AppData\Local\Temp\ipykernel_5060\2031040558.py:23: RuntimeWarning: invalid value encountered in true_divide
  comparison = (abs(stock_latest - stock_previous)/stock_previous) * 100


array([146720,  62178,  84542,  66192])

array([81759, 18830, 62929, 52630])

0         1         2         3      Warehouse
0  0.000000  0.000000  0.000000  0.000000     Wheel Pros
1  0.017831  0.188182  0.106046  0.024181         Turn14
2  0.040638  0.191185  0.058491  0.094519     Parts Auth
3  0.007908       NaN  0.007908  0.001551            PFG
4  0.027243  0.025641  0.028139  0.081348            NPW
5  0.020014  0.005778  0.033959  0.540814    Motor State
6  0.036534       NaN  0.036534  0.221586            LKQ
7  0.137867  0.431264  0.076826  0.185478       Keystone
8  0.007339  0.031874  0.000000  0.229380  Dorman Direct

0    1    2    3      Warehouse
0    0    0    0    0     Wheel Pros
1  106  471 -365  -17         Turn14
2 -217   73 -290 -426     Parts Auth
3   -7    0   -7    1            PFG
4  -80  -27  -53  -79            NPW
5   21    3   18  235    Motor State
6   28    0   28  151            LKQ
7  202  267  -65 -123       Keystone
8    6    6    0 -121  Dorman Direct

0_x  1_x  2_x  3_x      Warehouse       0_y       1_y       2_y       3_y
0    0    0    0    0     Wheel Pros  0.000000  0.000000  0.000000  0.000000
1  106  471 -365  -17         Turn14  0.017831  0.188182  0.106046  0.024181
2 -217   73 -290 -426     Parts Auth  0.040638  0.191185  0.058491  0.094519
3   -7    0   -7    1            PFG  0.007908       NaN  0.007908  0.001551
4  -80  -27  -53  -79            NPW  0.027243  0.025641  0.028139  0.081348
5   21    3   18  235    Motor State  0.020014  0.005778  0.033959  0.540814
6   28    0   28  151            LKQ  0.036534       NaN  0.036534  0.221586
7  202  267  -65 -123       Keystone  0.137867  0.431264  0.076826  0.185478
8    6    6    0 -121  Dorman Direct  0.007339  0.031874  0.000000  0.229380

Warehouse  Total in Main Difference  Not Added Difference  \
0     Wheel Pros                         0                     0   
1         Turn14                       106                   471   
2     Parts Auth                      -217                    73   
3            PFG                        -7                     0   
4            NPW                       -80                   -27   
5    Motor State                        21                     3   
6            LKQ                        28                     0   
7       Keystone                       202                   267   
8  Dorman Direct                         6                     6   

   Final Total Difference  In Stock Difference  Total in Main Difference %  \
0                       0                    0                    0.000000   
1                    -365                  -17                    0.017831   
2                    -290                 -426                    0.040638   
3                      -7                    1                    0.007908   
4                     -53                  -79                    0.027243   
5                      18                  235                    0.020014   
6                      28                  151                    0.036534   
7                     -65                 -123                    0.137867   
8                       0                 -121                    0.007339   

   Not Added Difference %  Final Total Difference %  In Stock Difference %  
0                0.000000                  0.000000               0.000000  
1                0.188182                  0.106046               0.024181  
2                0.191185                  0.058491               0.094519  
3                0.000000                  0.007908               0.001551  
4                0.025641                  0.028139               0.081348  
5                0.005778                  0.033959               0.540814  
6                0.000000                  0.036534               0.221586  
7                0.431264                  0.076826               0.185478  
8                0.031874                  0.000000               0.229380

#### Comparsion Table

In [100]:
import dataframe_image as dfi
comparison_df_styled = df_Inv_comparison.style.background_gradient(subset = ["Total in Main Difference %", "Not Added Difference %",
                                                                          "Final Total Difference %", "In Stock Difference %"], cmap="BuPu", vmin = 4.9, vmax = 5.0)
dfi.export(comparison_df_styled, 'comparison_Inventory_SKUs.png')
comparison_df_styled

#### Send update to slack Channel

In [ ]:
# import the slack_sdk module
import slack_sdk
from datetime import date

current_date = date.today()

def send_update_to_slack_channel(text, file, channelid):
    
    """Sends an update message and file to the specified Slack channel.

    Args:
    text : The text of the message to be sent.
    file : The file to be sent (e.g. "df_styled.png").
    channelid : The ID of the Slack channel to send the message and file to.

    Returns:
    str: A string indicating that the file was sent to the channel successfully.
    
    """
    # store the channel id for the slack channel where the message and file will be sent
    cid = channelid

    # create a client for the slack API using the WebClient class and the specified token
    c = slack_sdk.WebClient(token='xoxb-156915382752-4437979958069-2XlrUKvulSUOltDeqdlHrqjA')

    # create the text for the message to be sent, using the current date
    text = text

    # send a message to the specified slack channel with the created text
    c.chat_postMessage(channel=cid, text=text)

    # send the image file "df_styled.png" to the specified slack channel
    
    c.files_upload_v2(file=file, channels=cid)    
    
    return "File sent to channel successfully!"


slack_text = 'Inventory SKUs Comparison ' + current_date.strftime("%d-%m-%Y")
send_update_to_slack_channel(slack_text, "comparison_Inventory_SKUs.png", "C04D1HF1RHT")

## Output file:

In [22]:
options2 = webdriver.ChromeOptions()
options2.add_argument(r"--user-data-dir=C:\Users\Fahad Razzaq\AppData\Local\Google\Chrome\User Data\Output_comparison")


driver2 = webdriver.Chrome(options=options2)  #Opening selenium
driver2.get('https://www.channelspyder.com/inventory/inventory_list?file_type=3&upload_type=0&limit=200')    #Opening Amazon Inventory Page

In [23]:
def parse_output_summary(driver):
    """
    This function parses the webpage data using BeautifulSoup and stores it in a Pandas dataframe.
    
    Parameters:
    driver (WebDriver): A Selenium WebDriver object representing the current webpage.
    
    Returns:
    df (DataFrame): A Pandas DataFrame object containing the data from the webpage.
    """
    
    # Wait for the page to fully load before trying to parse the data
    WebDriverWait(driver, 300).until( lambda driver: driver.execute_script('return document.readyState') == 'complete')
    
    # Get the HTML source code of the page
    scr = driver2.page_source
    
    # Use BeautifulSoup to parse the HTML source code
    soup = BeautifulSoup(scr, 'lxml')
    
    # Find the div element with the class "main-container container-fluid"
    table =soup.find("div", attrs ={"class":"main-container container-fluid"})
    
    # Find all th (table header) elements within the div element
    headers = table.findAll('th')
    
    # Create a list of the header text, stripped of leading/trailing white space
    headerlist =[h.text.strip() for h in headers]
    
    # Find all tr (table row) elements within the div element
    rows = table.findAll('tr')[0:]
    
    # Create a list of lists, where each inner list represents a row of data
    records = [[td.getText().strip() for td in rows[i].findAll('td')[0:]] for i in range(len(rows))]
    
    # Create a Pandas DataFrame from the records list, using the headerlist as the column names
    df = pd.DataFrame(records, columns=headerlist)
    
    return df


#### Call function to parse output table

In [101]:
df_output = parse_output_summary(driver).loc[1:]
df_output['Total in Main'] = df_output['Total in Main'].astype(int)

df_output = df_output.loc[df_output['Total in Main'] >= 50000]
df_output

#           File Name      Channel/Warehouse    Type  Method  \
1      1            Download            1-AP Fusion  Output   Timer   
2      2            Download          BSAP Wal-Mart  Output   Timer   
3      3            Download  Part Synergy Wal-Mart  Output   Timer   
4      4  Download   +     -            1-BSAP eBay  Output   Timer   
5      5  Download   +     -           Part Synergy  Output   Timer   
..   ...                 ...                    ...     ...     ...   
193  193  Download   +     -           Part Synergy  Output  Manual   
194  194  Download   +     -    Part Synergy Amazon  Output  Manual   
198  198  Download   +     -    Part Synergy Amazon  Output  Manual   
199  199            Download            1-AP Fusion  Output   Timer   
200  200            Download          BSAP Wal-Mart  Output   Timer   

     Total in Main Not Added Final Total In Stock  \
1           205980      5912      200068   121046   
2            51727      4403       47324    33592   
3           289250      4789      284461   157279   
4          1346932   1342742        4190     4102   
5           291779     15791      275988   210842   
..             ...       ...         ...      ...   
193         288233     12261      275972   210505   
194        1420911      3913     1416998   572629   
198        1339207      3913     1335294   520549   
199         162402       661      161741    97634   
200          50156      1908       48248    33993   

                            Status             Uploaded  
1            Processed to APFusion  2023-01-05 21:31:35  
2        Success - Sent to Walmart  2023-01-05 21:15:34  
3        Success - Sent to Walmart  2023-01-05 20:31:34  
4    Success - Confirmed from EBAY  2023-01-05 20:01:35  
5    Success - Confirmed from EBAY  2023-01-05 19:19:34  
..                             ...                  ...  
193  Success - Confirmed from EBAY  2022-12-20 13:08:45  
194                 Success - Sent  2022-12-20 13:08:28  
198                 Success - Sent  2022-12-20 09:26:34  
199          Processed to APFusion  2022-12-19 21:30:26  
200      Success - Sent to Walmart  2022-12-19 21:16:27  

[174 rows x 11 columns]

In [108]:
df_output = parse_output_summary(driver).loc[1:]
df_output[df_output["Channel/Warehouse"] == 'BSAP Wal-Mart']

# File Name Channel/Warehouse    Type  Method Total in Main Not Added  \
2      2  Download     BSAP Wal-Mart  Output   Timer         51727      4403   
11    11  Download     BSAP Wal-Mart  Output   Timer         51728      1824   
20    20  Download     BSAP Wal-Mart  Output   Timer         51728      1824   
32    32  Download     BSAP Wal-Mart  Output   Timer         51750      1849   
41    41  Download     BSAP Wal-Mart  Output   Timer         51750      3799   
50    50  Download     BSAP Wal-Mart  Output   Timer         51750      3127   
59    59  Download     BSAP Wal-Mart  Output   Timer         51750      1812   
68    68  Download     BSAP Wal-Mart  Output   Timer         51762      1810   
77    77  Download     BSAP Wal-Mart  Output   Timer         51762      1800   
86    86  Download     BSAP Wal-Mart  Output   Timer         50086      1964   
96    96  Download     BSAP Wal-Mart  Output   Timer         50086      1914   
108  108  Download     BSAP Wal-Mart  Output   Timer         50111      1946   
118  118  Download     BSAP Wal-Mart  Output   Timer         34496      2676   
127  127  Download     BSAP Wal-Mart  Output   Timer         34496      2672   
136  136  Download     BSAP Wal-Mart  Output  Manual         34496      2671   
148  148  Download     BSAP Wal-Mart  Output   Timer         50156      1970   
158  158  Download     BSAP Wal-Mart  Output  Manual         50156      1970   
169  169  Download     BSAP Wal-Mart  Output  Manual         50156      1970   
175  175  Download     BSAP Wal-Mart  Output   Timer         50156      1956   
184  184  Download     BSAP Wal-Mart  Output   Timer         50156      1924   
200  200  Download     BSAP Wal-Mart  Output   Timer         50156      1908   

    Final Total In Stock                     Status             Uploaded  
2         47324    33592  Success - Sent to Walmart  2023-01-05 21:15:34  
11        49904    34520  Success - Sent to Walmart  2023-01-04 21:15:31  
20        49904    34639  Success - Sent to Walmart  2023-01-03 21:15:27  
32        49901    34683  Success - Sent to Walmart  2023-01-02 21:15:22  
41        47951    33919  Success - Sent to Walmart  2023-01-01 21:15:19  
50        48623    34134  Success - Sent to Walmart  2022-12-31 21:15:15  
59        49938    34808  Success - Sent to Walmart  2022-12-30 21:15:11  
68        49952    34804  Success - Sent to Walmart  2022-12-29 21:15:07  
77        49962    34844  Success - Sent to Walmart  2022-12-28 21:15:03  
86        48122    33903  Success - Sent to Walmart  2022-12-27 21:16:59  
96        48172    33951  Success - Sent to Walmart  2022-12-26 21:16:55  
108       48165    33916  Success - Sent to Walmart  2022-12-25 21:16:51  
118       31820    21248  Success - Sent to Walmart  2022-12-24 21:16:47  
127       31824    21234  Success - Sent to Walmart  2022-12-23 21:16:43  
136       31825    21230  Success - Sent to Walmart  2022-12-23 10:19:25  
148       48186    12651  Success - Sent to Walmart  2022-12-22 21:16:39  
158       48186    12657  Success - Sent to Walmart  2022-12-22 13:59:08  
169       48186    12657  Success - Sent to Walmart  2022-12-22 12:35:21  
175       48200    33940  Success - Sent to Walmart  2022-12-21 21:16:35  
184       48232    33966  Success - Sent to Walmart  2022-12-20 21:16:30  
200       48248    33993  Success - Sent to Walmart  2022-12-19 21:16:27

#### Comvert Categorical features into Numeric

In [102]:
df_output["Total in Main"] = df_output["Total in Main"].astype(int)
df_output["Final Total"] = df_output["Final Total"].astype(int)
df_output["Not Added"] = df_output["Not Added"].replace("N/A", 0)

df_output["Not Added"] = df_output["Not Added"].astype(int)
df_output["In Stock"] = df_output["In Stock"].astype(int)


df_output['Date'] = df_output['Uploaded'].apply(lambda x : pd.to_datetime(str(x)))
df_output['Date'] = df_output['Date'].dt.date

In [103]:
df_output = df_output.groupby(["Channel/Warehouse", "Date"]).head(1).sort_values(by = ["Channel/Warehouse", "Date"], ascending = False)
df_output

# File Name      Channel/Warehouse    Type Method  Total in Main  \
3      3  Download  Part Synergy Wal-Mart  Output  Timer         289250   
12    12  Download  Part Synergy Wal-Mart  Output  Timer         289228   
21    21  Download  Part Synergy Wal-Mart  Output  Timer         289228   
33    33  Download  Part Synergy Wal-Mart  Output  Timer         289245   
42    42  Download  Part Synergy Wal-Mart  Output  Timer         289245   
..   ...       ...                    ...     ...    ...            ...   
126  126  Download            1-AP Fusion  Output  Timer         117840   
147  147  Download            1-AP Fusion  Output  Timer         203144   
174  174  Download            1-AP Fusion  Output  Timer         203144   
183  183  Download            1-AP Fusion  Output  Timer         203144   
199  199  Download            1-AP Fusion  Output  Timer         162402   

     Not Added  Final Total  In Stock                     Status  \
3         4789       284461    157279  Success - Sent to Walmart   
12        2374       286854    158242  Success - Sent to Walmart   
21        2337       286891    158315  Success - Sent to Walmart   
33        2349       286896    158373  Success - Sent to Walmart   
42        2377       286868    158637  Success - Sent to Walmart   
..         ...          ...       ...                        ...   
126        497       117343     57137      Processed to APFusion   
147       4399       198745     52447      Processed to APFusion   
174       4399       198745    120970      Processed to APFusion   
183       4354       198790    120808      Processed to APFusion   
199        661       161741     97634      Processed to APFusion   

                Uploaded        Date  
3    2023-01-05 20:31:34  2023-01-05  
12   2023-01-04 20:31:31  2023-01-04  
21   2023-01-03 20:31:26  2023-01-03  
33   2023-01-02 20:31:23  2023-01-02  
42   2023-01-01 20:31:19  2023-01-01  
..                   ...         ...  
126  2022-12-23 21:30:43  2022-12-23  
147  2022-12-22 21:30:39  2022-12-22  
174  2022-12-21 21:30:35  2022-12-21  
183  2022-12-20 21:30:29  2022-12-20  
199  2022-12-19 21:30:26  2022-12-19  

[132 rows x 12 columns]

#### Conditional formatting on Comparison Table

In [104]:
dff_comparison = pd.DataFrame()
dff_diff = pd.DataFrame()

In [105]:
Channel_list = []
Comparison_list = []
difference = []


#Iterate over unique values in the "Channel/Warehouse" column of df_output

for label in df_output["Channel/Warehouse"].unique():

    stock_latest = df_output.loc[df_output["Channel/Warehouse"] == label, ['Total in Main', 'Not Added', 'Final Total', 'In Stock']].values[0]
    stock_previous = df_output.loc[df_output["Channel/Warehouse"] == label, ['Total in Main', 'Not Added', 'Final Total', 'In Stock']].values[1]
    
    diff_actual = stock_latest - stock_previous
    
    comparison = (abs(stock_latest - stock_previous)/stock_previous) * 100
    Comparison_list.append(comparison)
    difference.append(diff_actual)
    Channel_list.append(label)

    
dff_comparison = pd.DataFrame(Comparison_list)
dff_comparison['Channel'] = Channel_list

dff_diff  = pd.DataFrame(difference)
dff_diff['Channel'] = Channel_list

df_output_comparison = pd.merge(dff_diff, dff_comparison, on = "Channel")
df_output_comparison.columns = ['Total in Main Difference', 'Not Added Difference', 'Final Total Difference', 'In Stock Difference', 'Channel',
                                 'Total in Main Difference %', 'Not Added Difference %', 'Final Total Difference %', 'In Stock Difference %']
    
Channel = df_output_comparison.pop("Channel")
df_output_comparison.insert(0, 'Channel', Channel)

#### Conditional formatting on Comparison Table

In [106]:
import dataframe_image as dfi

# apply a background gradient style to the dataframe and store the resulting Styler object in the output_comparison variable
output_comparison = df_output_comparison.style.background_gradient(subset = ["Total in Main Difference %", "Not Added Difference %",
                                                                          "Final Total Difference %", "In Stock Difference %"], cmap="BuGn", vmin = 4.9, vmax = 5.0)

# export the styled dataframe to a PNG file
dfi.export(output_comparison, 'comparison_output_styled.png')

# display the styled dataframe
output_comparison

In [ ]:
# import the slack_sdk module

slack_text = 'Output Files Comparison ' + current_date.strftime("%d-%m-%Y")
send_update_to_slack_channel(slack_text, "comparison_output_styled.png", "C04D1HF1RHT")